version: "3.8"

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - ecommerce-microservices
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
    ports:
      - "5432:5432"
    volumes:
      - postgres_backup_data:/var/lib/postgresql/data
    networks:
      - ecommerce-microservices

volumes:
  postgres_backup_data:

networks:
  ecommerce-microservices:
    driver: bridge
