spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce?currentSchema=public
    username: postgres
    password: 1905
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: user-service

server:
  port: 8081